title: François-Xavier MAURICARD - Tech Lead & Project Manager
description: 20 years of software development experience | Tech Lead | Cloud Migration | Insurance & Banking
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
